DATA:
  DATASET: imagenet
MODEL:
  TYPE: vit_moe
  NAME: vit_moe_small_patch16_224_32expert_top1_4gpu_last2_C4
  VIT_MOE:
    EMBED_DIM: 512
    DEPTH: 8
    NUM_HEADS: 8
    MODE: 'Last2'
    NUM_LOCAL_EXPERTS: 8
    TOP_VALUE: 1
    CAPACITY_FACTOR: 4.0
    MOE_DROP: 0.0
    AUX_LOSS_WEIGHT: 0.01
TRAIN:
  EPOCHS: 150
  WARMUP_EPOCHS: 15