DATA:
  DATASET: imagenet
  IMG_SIZE: 192
MODEL:
  TYPE: swin_moge
  NAME: swin_moge_tiny_patch4_window12_192_32expert_4gpu_last2_C4_lr[default]-GSLW[0.4]-S[10-0.5-0.3]
  DROP_PATH_RATE: 0.2
  SWIN_MOGE:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 12
    MLP_FC2_BIAS: False
    MOE_BLOCKS: [ [ -1 ], [ -1 ], [ 5 ], [ 1 ] ]
    NUM_LOCAL_EXPERTS: 8
    TOP_VALUE: 1
    CAPACITY_FACTOR: 4.0
    IS_GSHARD_LOSS: False
    MOE_DROP: 0.1
    AUX_LOSS_WEIGHT: 0.01

    IS_GROUP_SPARSITY_LOSS: True
    GS_LOSS_WEIGHT: 0.4
    GS_WINDOW_SIZE: 3
    GS_STRIDE: 1
    GS_SIGMA_INIT: 10.0
    GS_SIGMA_FINAL: 0.5
    GS_SIGMA_POWER: 0.3
TRAIN:
  EPOCHS: 150
  WARMUP_EPOCHS: 15